### ISSUE TITLE
Error when try to import uPort

### ISSUE THREAD

**Issue by rinaldorossi** [ConsenSys/truffle-webpack-demo#16]
## Issue

Error on npm start

## Steps to Reproduce

import uPort lib in index.js

## Expected Behavior

No error on compile

## Actual Results

Failed to compile.

Error in ./~/uport-registry/build/contracts/UportRegistry.sol.js
Syntax error: Expected "contract", "import", "library", "pragma", "using", comment, end of input, end of line or whitespace but "v" found.
 @ ./~/uport-registry/lib/uportregistry.js 22:24-74

**Comment by johnmcdowall** [comment]
Sorry, not really relevant to this demo application. I suggest you raise an issue with the uPort team and see if they know what's going on.
