### ISSUE TITLE
Out-of-gas error when attempting build/start

### ISSUE THREAD

**Issue by uranther** [ConsenSys/truffle-webpack-demo#2]
I have `testrpc` running with default options, but have also tried seeding an account with millions of ETH and setting gasPrice to 0, but I still get the following error. It's not obvious from this project's or testrpc's README on how to avoid this issue.

```
▶ WEB3_RPC_LOCATION=http://localhost:8545 npm run start

> truffle-webpack@0.0.1 start /Users/jwheaton/Projects/truffle-webpack-demo
> node ./scripts/start.js

Starting the development server...

[TRUFFLE SOLIDITY] Searching for truffle.js
[TRUFFLE SOLIDITY] Found Truffle config at: /Users/jwheaton/Projects/truffle-webpack-demo/truffle.js
[TRUFFLE SOLIDITY] Setting network to 'default' for compilation and contract provisioning
[TRUFFLE SOLIDITY] Setting network_id to 'default' for compilation and contract provisioning
[TRUFFLE SOLIDITY] Compiling ConvertLib.sol...
[TRUFFLE SOLIDITY] Compiling MetaCoin.sol...
[TRUFFLE SOLIDITY] Compiling Migrations.sol...
[TRUFFLE SOLIDITY] Writing artifacts to ./../../../../var/folders/tv/62_htc9n00d5mmcq3j0bmlbsbcr9_3/T/webpack-truffle116911-33073-151iuhn
[TRUFFLE SOLIDITY] Running migration: 1_initial_migration.js
[TRUFFLE SOLIDITY]   Deploying Migrations...
[TRUFFLE SOLIDITY] Error encountered, bailing. Network state unknown. Review successful transactions manually.
[! TRUFFLE SOLIDITY ERROR] Error: VM Exception while processing transaction: out of gas
Failed to compile.

Error in ./contracts/MetaCoin.sol
Module build failed: Error: VM Exception while processing transaction: out of gas
 @ ./src/components/AccountList/AccountListContainer.js 33:16-49
```

**Comment by johnmcdowall** [comment]
I'm not experiencing this error. Can you please provide more details about what you are running against on port 8545, thanks!

**Comment by uranther** [comment]
Here's the output from `testrpc` after running the above command:

```
▶ testrpc
EthereumJS TestRPC v3.0.0

Available Accounts
==================
(0) 0x3394966f315637bba1c0e062d25f18ad6ec94428
(1) 0x9a4ce801c80e4b325ee4cc28512d564b946a465d
(2) 0x9d5e0b6d420f079e946455394e4859cf7f64d189
(3) 0x68f46bc22c2829d569e584eb7756e4133f2909d2
(4) 0xaa1085b67e7b27d2ea57d3e3b0e900258b852a9f
(5) 0x6c42921d435d27a363e4101385a4098e93c0b0cf
(6) 0x99353a6e0ff5d7fd307648e1faedf40d1f89eb07
(7) 0xdf611cb054cd36e35354ca484dd1afe0e131ef9b
(8) 0x10376147ca1b788352558f2736b501a287c6ada2
(9) 0x7832a75ff9e72ee43a5e0c2a1362eac0625a4e39

Private Keys
==================
(0) 918e6da1e761d59ed00c221e64eda15558c806d903893a4e40348b182389423b
(1) d18a9835c27a0845c2559a2d55b0c5361af6693a07cb82f294b727526e120359
(2) 875ad3bc63f3fcf50539aee33b711099ed9ba9c292d33faa6cf2aa484531330f
(3) cd3e103979293614e6b38f6c22ca25e166a2168d7b2414670e294dc9ba533bea
(4) d58546deb6f3f5e7c283ddf2cbd827a45f05c3008ff6b0661a3dda495c7a2612
(5) 018000ac46fdbb30eec2ab69e593bf72a295b0f093f825abfe6dc38c0f168b20
(6) 18c3582cf9914f24ea159837bb1b75f050673f1f6a077317e913b9b108d14d36
(7) 353c4af291f1fa985e9b4629500ae11f521165430906eaf8baf0453ff21f78ea
(8) 9aae50f469a6a3433141a56b0518c8985f26573a7393b13732975f77723d48c3
(9) b43afc4e72a96aa8019486bedc67b2d5e9d2977332ab2d75c73403d29f094391

HD Wallet
==================
Mnemonic:      denial disagree wage shadow dumb idle bronze table hotel empty design limit
Base HD Path:  m/44'/60'/0'/0/{account_index}

Listening on localhost:8545
eth_accounts
eth_sendTransaction

  Transaction: 0x3b26242e3e7e3283cf8270b6318f96b89eee83e1bd96459fa23fcdcbb8bc16ab
  Contract created: 0x3cca876e72368aa845867b4121cfe5936c7b199a
  Gas usage: 0x015f90
  Block Number: 0x01
  Block Time: Tue Oct 11 2016 16:13:57 GMT-0600 (MDT)
  Runtime Error: out of gas
```

**Comment by johnmcdowall** [comment]
`testrpc` 3.0.0 is unreleased beta. Do you get the same error running against the current release of testrpc?

**Comment by chevdor** [comment]
Hello @uranther,

First of all, the issue you are running into has little to do with your balance. You will be fine with 1 ETH, you don´t need millions 😄 
Also you can ignore the gas price, this is not the issue if you use the default values.

I would suggest the following, you will need to do that for each contract of your project:
* Take a look at the testrpc output for a given contract
* You will see something like:
```
Transaction: 0xd15c33abe7e4c7706837c30d64ab8abc7935487908a0c9ac633cc00bda96854c
  Contract created: 0x65317e699b00bcbd6bd3b1590daba63f15d49d64
  Gas usage: 0x025990
  Block Number: 0x57
  Block Time: Wed Oct 12 2016 10:33:25 GMT+0200 (CEST)
  Runtime Error: out of gas
```
* Convert 0x025990 to decimal, that´s 154000. That means, that 154k is not enough gas to deploy this specific contract (This is THE Migration contract)
* In your migrations files, change each deploy from:
```
module.exports = function(deployer) {
  deployer.deploy(Migrations);
};
```
to
```
module.exports = function(deployer) {
  deployer.deploy(Migrations, {gas: 155000});
};
```
* Try to run `npm run dev` again

NOTE: If you don´t know the amount of gas needed, you may need to either estimate it or go through trial and error. Also note that if you set a Limit to 15k gas (just an example), the tx will fail saying it is out of gas after 15k, which gives you no information on the real amount of gas needed.
You can also start with a high value such as 4.5M (4500000) and see the real usage in the output of testrpc.

**Comment by uranther** [comment]
Looks like TestRPC v3.0.0 was released a week ago, and with breaking changes: https://github.com/ethereumjs/testrpc/releases/tag/v3.0.0

@chevdor Your suggestions fix my issue if I give it a high enough amount of gas. So an appropriate gas amount needs to be added to those migration files to catch up with the latest TestRPC (which made breaking changes to match geth).

Thanks for the help guys!

**Comment by johnmcdowall** [comment]
@uranther Uggh, you're right! Sorry, working on too many projects starting with T and confused it with Truffle haha. Will look into this shortly.

**Comment by johnmcdowall** [comment]
@uranther Ok this should be fixed in  9793c45 - please pull the latest and let me know how you get on!

**Comment by johnmcdowall** [comment]
Closing this now, feel free to reopen if still an issue.

**Comment by aliaksandr-adzinets** [comment]
Hello

I am using TestRPC 3.0.3 with Truffle 3.0.0.4 and I'm getting "out of gas" in browser's console:

```
Error: VM Exception while processing transaction: out of gas
Stack trace:
Error: VM Exception while processing transaction: out of gas
    [200]</module.exports.InvalidResponse@http://localhost:8080/app.js:37995:16
    [219]</RequestManager.prototype.sendAsync/<@http://localhost:8080/app.js:40919:29
    require<[32]</i.prototype.sendAsync/n.onreadystatechange@http://localhost:8080/app.js:5319:8205
From previous event:
    [1]</</Utils.promisifyFunction/<@http://localhost:8080/app.js:5391:1
    updateMP@http://localhost:8080/app.js:44242:5
    onclick@http://localhost:8080/:1:1

```
when calling updateMP() method of the following contract:

```
pragma solidity ^0.4.7;

contract Accounts {

    struct MP {
        string name;
        string email;
        address addr;
        bool registered;
        int i;
    }

    mapping (address => MP) mps;
    
    function updateMP(
        string name, string email, int i) {
        
        mps[msg.sender].name =  name;
        mps[msg.sender].email =  email;
        mps[msg.sender].addr = msg.sender;
        mps[msg.sender].registered = true;
        mps[msg.sender].i = i;
    }
    
    function getMP() constant returns (
        string name, string email, address addr, bool registered, int i) {
        
        name = mps[msg.sender].name;
        email = mps[msg.sender].email;
        addr = mps[msg.sender].addr;
        registered = mps[msg.sender].registered;
        i = mps[msg.sender].i;
    }
    
}
```

TestRPC output:

```
eth_sendTransaction

  Transaction: 0xbf8eaf307100bc679c4772cbb315d9499164bb1984cc828a201bd2600f6bd98a
  Gas usage: 0x015f90
  Block Number: 0x05
  Block Time: Thu Dec 22 2016 23:01:35 GMT+0300 (+03)
  Runtime Error: out of gas
```

Interesting thing is that if I remove the email field out of everywhere (struct, params) the error is not thrown. Please advice.

**Comment by plingampally** [comment]
I was having the same problem, a clean pull does not build with `Truffle v3.1.2` and `EthereumJS TestRPC v3.0.3`. 

Fixed the issue by upping the gas in `truffle.js`

**Comment by aliaksandr-adzinets** [comment]
plingampally, 
yes the problem was too low gas provided on the contract creation in truffle.js -- and that is why I got it working when I removed the email field. simple X)

**Comment by eolszewski** [comment]
@plingampally fancy seeing you here

**Comment by JohnAllen** [comment]
Noob here: shouldn't I be able to run `testrpc --gasPrice 0` and the gas becomes irrelevant during development?  And I've read that `out of gas` can be an erroneous error message?

**Comment by aliaksandr-adzinets** [comment]
@JohnAllen 
No, you shouldn't. You have to pay N ethers to send a transaction, where N = gas x gasPrice, so if you set gasPrice=0, any attempt will fail with "out of gas".
