### ISSUE TITLE
Could not find built Migrations contract

### ISSUE THREAD

**Issue by OR13** [ConsenSys/truffle-webpack-demo#3]
After cloning and running npm install,

```
$ WEB3_RPC_LOCATION=http://localhost:8545 npm run start
```

Results in:

```
> node ./scripts/start.js

Starting the development server...

[TRUFFLE SOLIDITY] Searching for truffle.js
[TRUFFLE SOLIDITY] Found Truffle config at: /Users/USER/truffle-webpack-demo/truffle.js
[TRUFFLE SOLIDITY] Compiling ConvertLib.sol...
[TRUFFLE SOLIDITY] Compiling MetaCoin.sol...
[TRUFFLE SOLIDITY] Compiling Migrations.sol...
[! TRUFFLE SOLIDITY ERROR] Error: Could not find built Migrations contract.
Failed to compile.

Error in ./contracts/MetaCoin.sol
Module build failed: Error: Could not find built Migrations contract.
 @ ./src/components/AccountList/AccountListContainer.js 33:16-49
```

I'm brand new to truffle, so apologies if this suggests something obvious.

**Comment by willwarren89** [comment]
+1 bump

**Comment by johnmcdowall** [comment]
@QR13 Can you try pulling the latest version and see how that goes? I just bumped the version on `truffle-solidity-loader`.

**Comment by johnmcdowall** [comment]
@OR13 I'm guessing this was because the contract ran out of gas - can you try pulling the latest version which uses an updated loader and a default gas value

**Comment by willwarren89** [comment]
Switching from version 0.0.4 to 0.0.7 seemed to fix the issue. I also manually specified the amount of gas to be used during the deployment of contracts within the migrations files.  Also, to comply with the latest version of the solidity compiler (solc ^0.4.0) the solidity files must be updated accordingly:

- Add `pragma solidity ^0.4.0;` to the top of each .sol file

- The restricted() modifier in Migrations.sol is missing a semicolon and must be changed to `modifier restricted() {
    if (msg.sender == owner) _;
  }`

**Comment by johnmcdowall** [comment]
@willwarren89 0.0.7 also now respects `gas` configurations in the `truffle.js` config file fwiw. 

Closing this now, feel free to reopen if still an issue.

**Comment by OR13** [comment]
@johnmcdowall Thanks, the issue has been resolved.
