### ISSUE TITLE
Update contracts to comply with latest solidity compiler (solc: ^0.4.0)

### ISSUE THREAD

**Issue by willwarren89** [ConsenSys/truffle-webpack-demo#4]
To comply with the latest version of the solidity compiler (solc ^0.4.0) the solidity files must be updated accordingly:

- Add `pragma solidity ^0.4.0;` to the top of each .sol file

- The restricted() modifier in Migrations.sol is missing a semicolon and must be changed to `modifier restricted() { if (msg.sender == owner) _; }`

**Comment by caleteeter** [comment]
Submitted a PR for these changes.

**Comment by johnmcdowall** [comment]
Thanks @caleteeter, merged!
